apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api

spec:
  replicas: 4
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: samsonnegedu/auth-manager-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: postgres-configuration
